# Generated by Django 3.1.1 on 2020-09-19 22:01

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200917_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
