# Generated by Django 3.1.1 on 2020-09-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200919_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Icon',
        ),
    ]
