# Generated by Django 3.1.1 on 2020-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200919_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_needed',
            field=models.TimeField(default='00:30'),
        ),
    ]
